modLoader = "javafml"
loaderVersion = "[40,)"
license = "GNU LGPLv3"
issueTrackerURL = "http://github.com/iCrazyBlaze/"

[[mods]]
modId = "modlistpaste"
version = "${file.jarVersion}"
displayName = "Mod List Paster"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/mod-list-paster"
logoFile = "logo.png"
credits = "Idea from MMD"
authors = "RonaRage, AKA Btarg"
description = '''
Save a list of your currently installed mods to the clipboard or to a text file.
'''

[[dependencies.modlistpaste]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.modlistpaste]]
modId="minecraft"
mandatory=true
versionRange="[1.18,1.19)"
side="CLIENT"
